<a href="https://colab.research.google.com/github/KAMBLE/ChatBot/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy.linalg import eig

In [3]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
# calculate the mean of each column
M = np.mean(A.T, axis=1)
print(M)

[3. 4.]


In [6]:
# center columns by subtracting column means
C = A - M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [10]:
# calculate covariance matrix of centered matrix
V = np.cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [13]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]


In [14]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


Using inbuilt functionality 

In [0]:
from sklearn.decomposition import PCA

In [17]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [0]:
# create the PCA instance
pca = PCA(2)

In [22]:
# fit on data
pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [23]:
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]


In [24]:
# transform data
B = pca.transform(A)
print(B)

[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]
